### ISSUE TITLE
How can I include XML declaration with serializeToString()?

### ISSUE THREAD

**Issue by johnballantyne** [jindw/xmldom#135]
Here's a simplified example of the code I'm using to build an XML Document:

    var xmldom = require('xmldom');
    var XMLDoc,
        example;

    XMLDoc = new xmldom.DOMImplementation().createDocument(null, null, null);
    XMLDoc.appendChild(XMLDoc.createProcessingInstruction('xml-stylesheet', 'type="text/xsl'));

    example = XMLDoc.createElement('foo');
    example.appendChild(XMLDoc.createTextNode('bar'));
    XMLDoc.appendChild(example);

    console.log(new xmldom.XMLSerializer().serializeToString(XMLDoc));

Here's the output:

    <?xml-stylesheet type="text/xsl?><foo>bar</foo>

This is what I would like the output to look like:

    <?xml version="1.0" ?><?xml-stylesheet type="text/xsl?><foo>bar</foo>

What is required to include the XML declaration when using `serializeToString()`? I could use `createProcessingInstruction()`, but I'm not confident that would be [the right way](https://en.wikipedia.org/wiki/Processing_Instruction#Syntax).

> "The XML Declaration at the beginning of an XML document is not a processing instruction, however its similar syntax has often resulted in it being referred to as a processing instruction."

The .NET XML library has a [`CreateXmlDeclaration()` Method](https://msdn.microsoft.com/en-us/library/system.xml.xmldocument.createxmldeclaration(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2), but I'm not seeing anything that functionality available in xmldom. Am I overlooking something or should I just use `createProcessingInstruction()`?

**Comment by jindw** [comment]
var xmldom = require('xmldom');
var XMLDoc,
    example;

XMLDoc = new xmldom.DOMImplementation().createDocument(null, null, null);
XMLDoc.appendChild(XMLDoc.createProcessingInstruction('xml', 'version="1.0'));
XMLDoc.appendChild(XMLDoc.createProcessingInstruction('xml-stylesheet', 'type="text/xsl'));

example = XMLDoc.createElement('foo');
example.appendChild(XMLDoc.createTextNode('bar'));
XMLDoc.appendChild(example);

console.log(new xmldom.XMLSerializer().serializeToString(XMLDoc));
