### ISSUE TITLE
attribute "default" missed value!! "default" instead!!

### ISSUE THREAD

**Issue by EvanFreeman** [jindw/xmldom#140]
This error occurs on parseFromString(html, 'text/html') on track tags that have the property default set.

<track src="..." default></track>

because it can't parse the default correctly unless its default="default", though it is correct according to the w3c

**Comment by jindw** [comment]
please submit a simple reproduction code

**Comment by Gcaufy** [comment]
```
<test hidden ></test>
```
This will cause the warning

**Comment by gaggle** [comment]
I also experience this. @jindw, should this issue be re-opened after @Gcaufy updated it?
