### ISSUE TITLE
xmldom breaks SVG images by incorrectly closing empty defs tags

### ISSUE THREAD

**Issue by timfish** [jindw/xmldom#141]
I've been trying to remove some attributes from SVG images before inlining them in HTML but they no longer display in Chrome after passing through xmldom (I'm passing the `image/svg+xml` MIME type btw)

They all have empty defs tags `<defs id="defs14" />` which xmldom closes AFTER all the paths. With all the paths now contained in the `defs` tag they are no longer displayed. Interestingly I also see the same behavior in cheerio 0.19 but don't see any common dependencies.

Before:
```
<svg>
  <metadata>...</metadata>
  <defs id="defs14" />
  <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />
  <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />
</svg>
```
After:
```
<svg>
  <metadata>...</metadata>
  <defs id="defs14">
    <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />
    <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />
  </defs>
</svg>
```

**Comment by jindw** [comment]
are you sure the <defs tag is closed??
i can not Reproduction it:(


var DomParser = require("xmldom").DOMParser;
var parser = new DomParser();
var svgCase = [
'<svg>',
'  <metadata>...</metadata>',
'  <defs id="defs14"/>',
'  <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />',
'  <path id="path4" d="M 68.589358,...-6.363961,-6.363964 z" />',
'</svg>'
].join('\r\n')
