### ISSUE TITLE
Endless loop, node crashes with out of memory

### ISSUE THREAD

**Issue by teobugslayer** [jindw/xmldom#142]
Repro case

```
var fileContents = '<Page><Label class="title"/></Page';

var domErrorHandler = function(level, str) { console.log("x"); };
var DomParser = require("xmldom").DOMParser;
var parser = new DomParser({ locator:{}, errorHandler: domErrorHandler });
parser.parseFromString(fileContents, "text/xml");
```

This makes node to allocate endlessly memory until the process crashes. If the attribute in the inner tag is removed, https://github.com/jindw/xmldom/issues/139 happens instead.

This is blocker for us, because it triggers https://github.com/NativeScript/nativescript-cli/issues/1307

**Comment by teobugslayer** [comment]
Happens with node 4.2.3 on Windows, or node 0.12 on OS X.

**Comment by jindw** [comment]
thanks for your report!
it's a serious bug!!

fixed !
