### ISSUE TITLE
Attributes in xml namespace (xml:id, xml:space, xml:lang)

### ISSUE THREAD

**Issue by michaelhkay** [jindw/xmldom#147]
When an attribute is prefixed "xml", the DOM Attr node has the namespaceURI property value "undefined", and the method getAttributeNS("http://www.w3.org/XML/1998/namespace", "lang") on the containing element does not retrieve the attribute. This is surely incorrect: the xml prefix is implicitly bound to the namespace "http://www.w3.org/XML/1998/namespace"

**Comment by jindw** [comment]
fixed 0.1.21
thanks
