### ISSUE TITLE
Infinite loop when parsing invalid XML

### ISSUE THREAD

**Issue by pawelgrzes** [jindw/xmldom#157]
For some inputs there is an infinite loop in `position(p,m)` function inside `parse(source,defaultNSMapCopy,entityMap,domBuilder,errorHandler)` function (file `sax.js`)

Steps to reproduce:
`new DOMParser().parseFromString('<a');`

**Comment by dap** [comment]
This can result in a denial of service for applications depending on xmldom for indication of input validity.

**Comment by SirLenz0rlot** [comment]
I saw a similar infinite loop with `new DOMParser().parseFromString(1);`

my terminal keeps logging, which I can trace back to the `sax.js` @pawelgrzes refers to.

     @#[line:0,col:1]
     [xmldom error]	element parse error: TypeError: source.indexOf is not a function

**Comment by jindw** [comment]
fixed in new release
thanks
