### ISSUE TITLE
Usage in React Native

### ISSUE THREAD

**Issue by frankbolviken** [jindw/xmldom#163]
Hi,

Currently looking for frameworks to parse string to xml in react native.
I can't seem to find any frameworks that works. 
How much effort do you think that it will take to make this work in React Native?

**Comment by gcrabtree** [comment]
@frankbolviken It is not difficult at all. 

Just install and consume.

I had to add it to the window global for a module that depended on it, like so:
`window.DOMParser = require('xmldom').DOMParser;`

Worked great. I'd close this as an issue.

**Comment by BrendanBerkley** [comment]
@frankbolviken Consult [this example](https://github.com/kaich/ASReact/blob/master/App/Main/TypePage.js) to see xmldom in action for React Native.
