### ISSUE TITLE
Handle whitespace

### ISSUE THREAD

**Issue by wshager** [jindw/xmldom#175]
Is there a way to ignore whitespace when parsing? Currently all whitespace seems to be left intact as text nodes. Also, when serializing, whitespace is still there when nodes are removed.

**Comment by jindw** [comment]
sorry, no way.

**Comment by pft** [comment]
Seems pretty easy, looking at https://github.com/jindw/xmldom/pull/92.

However, xml:space="preserve" would with that pull request then be ignored, so I kind off understand jindw's reluctance.

https://www.npmjs.com/package/dom-whitespace can remove all whitespace (also the ones with xml:space="preserve") after parsing.
