### ISSUE TITLE
[TAG] Latest npm release 0.1.22

### ISSUE THREAD

**Issue by shazron** [jindw/xmldom#177]
This was the last commit for v0.1.22:
https://github.com/jindw/xmldom/commit/29a83b315aef56c156602286b2d884a3b4c2521f

sha1 verified using `npm info xmldom`

Fix:
`git tag 0.1.22 29a83b3`
`git push origin 0.1.22`

**Comment by jindw** [comment]
I released an updated version

**Comment by shazron** [comment]
Hi, thanks. I don't see the tag for the latest release? (your last tag was 2013)
