### ISSUE TITLE
Publish new build

### ISSUE THREAD

**Issue by rmhrisk** [jindw/xmldom#179]
There are several fixes, for example #166 that have been fixed in the current code base. We have been using the xmldom-alpha package you have created to work around these but it is problematic it has a different name.

For example our travis builds are broken on our XMLDSIG implementation on linux; for some magical reason linux is getting the xmldom release and not xmldom-alpha.

You had stated previously your concern was stability of the alpha release, we have been using it since you published with no issues.

Please consider publishing a new formal XMLDOM release.

**Comment by jindw** [comment]
new version is published！
