### ISSUE TITLE
When  parsing Large XML files in node.js, i got the following error

### ISSUE THREAD

**Issue by sekarraj1** [jindw/xmldom#180]
[xmldom error]  element parse error: TypeError: Cannot read property 'localNSMap' of undefined

**Comment by jindw** [comment]
may be some xml syntax error.

Give a simplified error case, otherwise I can't check

**Comment by sekarraj1** [comment]
I have extracted details from XML file based on select and XPATH method in
node.js where i have hard coded URL link(from xml file).

is there any other method to get the details without hardcoding the URL
link.

const select = xpath.useNamespaces({ 'ITRForm':
*'http://incometaxindiaefiling.gov.in/master
<http://incometaxindiaefiling.gov.in/master>*' });
                    assyear[i] = select('//ITRForm:AssessmentYear/text()',
doc)[0].nodeValue;
