### ISSUE TITLE
parseFromString() results in 100% CPU load when parsing broken html-file

### ISSUE THREAD

**Issue by m-abs** [jindw/xmldom#187]
If parseFromString() is called with a XML-string ending with an unclosed element, xmldom starts using 100% CPU.

It looks like https://github.com/jindw/xmldom/blob/master/sax.js#L69 goes into an infinite loop.
I tried printing the parameters for the loop and `p >= lineEnd` is always true and `m` keep matching the same part of the string.

Example code:
```javascript
'use strict';

const xmldom = require('xmldom');
const data = '<foo';

console.log(new xmldom.DOMParser().parseFromString(data));
```

**Comment by jindw** [comment]
thanks 
bug fixed in the new version!
