### ISSUE TITLE
Symbol.iterator on NodeList

### ISSUE THREAD

**Issue by MoritzKn** [jindw/xmldom#189]
In the modern browsers it is possible to do:
```js
let myArray = [...doc.getElementsByTagName('foo')]
```
It would be cool if this package would support this too.
Therefore the [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) has to be defined on the the `NodeList`.

**Comment by jindw** [comment]
it is base on w3c dom level2 .
Modifying the interface will lead to compatibility issues
