### ISSUE TITLE
Namespace duplication in serialization

### ISSUE THREAD

**Issue by zorkow** [jindw/xmldom#191]
Namespaces are output twice, once as a regular attribute, once as a single quoted "attribute", in string serialization.
Error occurred when moving to from package 0.1.22 to 0.1.24. 

Minimal example:

      xmldom = require('xmldom');
      var dp = new xmldom.DOMParser();
      var doc = dp.parseFromString('<math xmlns="http://www.w3.org/1998/Math/MathML"><mn>1</mn></math>', 'text/xml');
      doc.toString();

yields

     <math xmlns="http://www.w3.org/1998/Math/MathML" xmlns=\'http://www.w3.org/1998/Math/MathML\'><mn>1</mn></math>

All other behaviour involving namespaces seems to be unaffected.

**Comment by jindw** [comment]
sorry
testcase added!!
I'll fix that right now.

**Comment by jindw** [comment]
fixed!!
v0.1.25

**Comment by zorkow** [comment]
Great. Thanks for the quick turnaround.
Works fine for v0.1.25/26/27.
