### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by codler** [jindw/xmldom#218]
Possible to release a new version to NPM?

**Comment by mems** [comment]
It's appears the package's name change to [`xmldom-alpha`](https://www.npmjs.com/package/xmldom-alpha)

**Comment by amitguptagwl** [comment]
This project is not active anymore. You can try [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser/issues/134) instead

**Comment by codler** [comment]
Seems to have been moved to https://github.com/xmldom/xmldom
