### ISSUE TITLE
0.1.28 is not on npm?

### ISSUE THREAD

**Issue by gaggle** [jindw/xmldom#225]
Hi,

Was the most recent changes not pushed to npm? Npm has latest version as 0.1.27, but this repo's latest version states 0.1.28.

EDIT: Ah repo version is in alpha?

(and thanks for making this library)

**Comment by mems** [comment]
It's appears the package's name change to [`xmldom-alpha`](https://www.npmjs.com/package/xmldom-alpha)

See #218

**Comment by karfau** [comment]
@mems @gaggle 
See https://github.com/jindw/xmldom/issues/259
There also has been a security issue that affects all xmldom and xmldom-alpha packages before version 0.5.0, so please avoid using xmldom-alpha since it is no longer maintained.
